# GENERATED FILE!
# Edit xtask/src/update.rs to maintain this file

[package]
name = "lumo-icons"
version = "0.8.0"
description = "Lumo icons for leptos"
authors = ["James <lumo.trade>"]
readme = "README.md"
repository = "https://github.com/cornfoo/lumo-icons"
keywords = ["icons", "leptos", "lumo"]
edition = "2021"
license = "MIT"
exclude = ["/core"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.7.8", features = ["csr", "nightly"] }
serde_json = "1"

[workspace]
members = ["xtask"]

[features]
default = ["all"]
all = [
	"core",
	"flags",
	"micro-bold",
	"ui",
	"uncategorized"
]
core = []
flags = []
micro-bold = []
ui = []
uncategorized = []
